baseURL = "https://nparisi.netlify.app/" # https://nparisi.netlify.app/ | https://localhost
languageCode = "it-IT"
title = "nParisi.com // il blog"
theme = "tracks"
publishDir = "blog"

disqusShortname = "nparisi-com" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-128082042-1" # Enable Google Analytics by entering your tracking code
preserveTaxonomyNames = true
paginate = 7 # Numero di post per pagina

[taxonomy]
    category    =   "categories"
    tag         =   "tags"

[permalinks]
    # Non modificare
    categories = "/:slug"
    tags = "/:slug"
    # /Non modificare

    post = "/:filename"
#    page = "/:slug/"
#    post =   "/:section/:slug"

[privacy]
    # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
    # Informazioni sui Cookie: https://www.giovannifracasso.it/accettazione-cookies-privacy-banner
    # Test pagina per cookie: https://webcookies.org/
    # Verifica i cookie creati: https://www.cookiemetrix.com/
    [privacy.googleAnalytics]
        disable = false # set to true to disable service 
        anonymizeIP = true # set to true to meet General Data Protection Regulation (GDPR)
        respectDoNotTrack = false
        useSessionStorage = false

[params]
    author = "Nicola"
    image  = "/img/logo_1x1.png"
    slogan = "tecnologia / medicina / viaggi / fotografia"
    copyright = [
        "&copy; 2018-YEAR NICOLA PARISI" ,
        "Tutte le foto - se non diversamente specificato - sono di mia proprietà. E' vietata la riproduzione anche parziale dei contenuti di questo blog." ,
        "[Disclaimer](/disclaimer) &nbsp; | &nbsp; [Licenza](/licenza) &nbsp; | &nbsp; [Privacy](/privacy) &nbsp; | &nbsp; [Caffè?](/caffe)"
    ]

# Nav links in the side bar
[[menu.main]]
    name = "Tutti i post"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "travel/"
    weight = 2

    [[menu.main]]
    name = "Destinazioni e racconti"
    parent = "travel"
    url = "racconti-di-viaggio/"
    weight = 2

    [[menu.main]]
    name = "Travel tips"
    parent = "travel"
    url = "travel-tips/"
    weight = 2

    [[menu.main]]
    name = "Accessori"
    url = "accessori/"
    weight = 3

    [[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "blog/"
    weight = 5

    [[menu.main]]
    name = "Libri"
    parent = "blog"
    url = "libreria/"
    weight = 5

    [[menu.main]]
    name = "Lifestyle"
    parent = "blog"
    url = "lifestyle/"
    weight = 5

    [[menu.main]]
    name = "Med & Tech"
    url = "med-tech/"
    weight = 6

    [[menu.main]]
    name = "Chi sono"
    url = "about/"
    weight = 7


# this will also be in author bio if there is no writer.
[params.social]
    twitter       = "https://twitter.com/np_melanogaster"
    instagram     = "https://instagram.com/npmelano"
    youtube       = "https://www.youtube.com/channel/UCz_ZsgGRbD4tC8_-4Ni78hQ"
    rss           = true
    contatti      = "email/"
    telegram      = "https://t.me/nparisi"