baseURL = "https://nparisi.com/" # https://nparisi.netlify.app/ | https://localhost
languageCode = "it-it"
defaultContentLanguage = "it"
title = "nParisi.com // il blog"
theme = "tracks"
publishDir = ""

disqusShortname = "nparisi-com"
googleAnalytics = "UA-128082042-1"

preserveTaxonomyNames = true
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true
disableKinds = ["taxonomyTerm"]

paginate = 7

timeout = 120000

[taxonomy]
    category    =   "categories"
    tag         =   "tags"

[permalinks]
    categories = "/:slug"
    tags = "/tags/:slug"

[privacy]
    # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
    # Informazioni sui Cookie: https://www.giovannifracasso.it/accettazione-cookies-privacy-banner
    # Test pagina per cookie: https://webcookies.org/
    # Verifica i cookie creati: https://www.cookiemetrix.com/
    [privacy.googleAnalytics]
        disable = false # set to true to disable service 
        anonymizeIP = true # set to true to meet General Data Protection Regulation (GDPR)
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
    [privacy.vimeo]
        disable = false
        simple = false

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[params]
    author = "Nicola"
    image  = "/images/logo_1x1.png"
    slogan = "tecnologia / libri / viaggi / fotografia"
    copyright = [ # esiste un copyright anche in scripts.html nella gallery full screen
        "&copy; 2018-YEAR NICOLA PARISI" ,
        "Tutte le foto - se non diversamente specificato - sono di mia proprietà. E' vietata la riproduzione anche parziale dei contenuti di questo blog." ,
        "[Disclaimer](/disclaimer) &nbsp; | &nbsp; [Licenza](/licenza) &nbsp; | &nbsp; [Privacy](/privacy) &nbsp; | &nbsp; [Sorgenti](/sorgenti) &nbsp; | &nbsp; [Caffè?](/caffe)"
    ]
    description = "Un blog, un diario, una raccolta di foto che parlano di viaggi, fotografia, avventure, tecnologia e libri."

    instagramAppId  = "5697953803609352"
    instagramClientToken    = "5a4d16aa5e39c88d96f2e44b5a8716a8"

    RSSLink =   true

[[menu.main]]
    name = "Tutti i post"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/tags/travel/"
    weight = 2

    [[menu.main]]
    name = "Destinazioni e racconti"
    parent = "travel"
    url = "destinazioni/"
    weight = 1

    [[menu.main]]
    name = "Compagnie aeree"
    parent = "travel"
    url = "compagnie-aeree/"
    weight = 2

    [[menu.main]]
    name = "Travel tips"
    parent = "travel"
    url = "travel-tips/"
    weight = 3

    [[menu.main]]
    name = "Accessori"
    identifier = "accessori"
    url = "accessori/"
    weight = 3

#    [[menu.main]]
#    name = "Zaini e bags"
#    parent = "accessori"
#    url = "/tags/zaini-bags"
#     weight = 1

    [[menu.main]]
    name = "Fotografia"
    parent = "accessori"
    url = "/accessori/attrezzatura-fotografica"
    weight = 1

#    [[menu.main]]
#    name = "Workstation"
#    parent = "accessori"
#    url = "/accessori/workstation"
#    weight = 3

    [[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/tags/blog/"
    weight = 4

    [[menu.main]]
    name = "Libreria"
    parent = "blog"
    url = "libreria/"
    weight = 1

    [[menu.main]]
    name = "Lifestyle"
    parent = "blog"
    url = "lifestyle/"
    weight = 2

    [[menu.main]]
    name = "#Liquori d'Europa"
    parent = "blog"
    url = "tags/liquorideuropa"
    weight = 3

    [[menu.main]]
    name = "#worldseaschallange"
    parent = "blog"
    url = "lifestyle/worldseaschallange/"
    weight = 4

    [[menu.main]]
    name = "Med & Tech"
    url = "med-tech/"
    weight = 5

    [[menu.main]]
    name = "Chi sono"
    url = "about/"
    weight = 6

[params.social]
    twitter       = "nparisicom"
    instagram     = "npmelano"
    youtube       = "UCz_ZsgGRbD4tC8_-4Ni78hQ"
    rss           = true
    contatti      = "email/"
    telegram      = "nparisi"