baseURL = "https://nparisi.netlify.app/" # https://nparisi.netlify.app/ | https://localhost
languageCode = "it-it"
title = "nParisi.com // il blog"
theme = "tracks"
publishDir = ""

disqusShortname = "nparisi-com"
googleAnalytics = "UA-128082042-1"

preserveTaxonomyNames = true
enableRobotsTXT = true
canonifyURLs = true

disableKinds = ["taxonomyTerm"]

paginate = 7

[taxonomy]
    category    =   "categories"
    tag         =   "tags"

[permalinks]
    categories = "/:slug"
    tags = "/tags/:slug"

[privacy]
    # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
    # Informazioni sui Cookie: https://www.giovannifracasso.it/accettazione-cookies-privacy-banner
    # Test pagina per cookie: https://webcookies.org/
    # Verifica i cookie creati: https://www.cookiemetrix.com/
    [privacy.googleAnalytics]
        disable = false # set to true to disable service 
        anonymizeIP = true # set to true to meet General Data Protection Regulation (GDPR)
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
    [privacy.vimeo]
        disable = false
        simple = false

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[params]
    author = "Nicola"
    image  = "/img/logo_1x1.png"
    slogan = "tecnologia / libri / viaggi / fotografia"
    copyright = [
        "&copy; 2018-YEAR NICOLA PARISI" ,
        "Tutte le foto - se non diversamente specificato - sono di mia proprietà. E' vietata la riproduzione anche parziale dei contenuti di questo blog." ,
        "[Disclaimer](/disclaimer) &nbsp; | &nbsp; [Licenza](/licenza) &nbsp; | &nbsp; [Privacy](/privacy) &nbsp; | &nbsp; [Sorgenti](/sorgenti) &nbsp; | &nbsp; [Caffè?](/caffe)"
    ]
    description = "Blog personale che parla di viaggi, fotografia, tecnologia, libri"

[[menu.main]]
    name = "Tutti i post"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/tags/travel/"
    weight = 2

    [[menu.main]]
    name = "Destinazioni e racconti"
    parent = "travel"
    url = "racconti-di-viaggio/"
    weight = 2

    [[menu.main]]
    name = "Travel tips"
    parent = "travel"
    url = "travel-tips/"
    weight = 2

    [[menu.main]]
    name = "Accessori"
    url = "accessori/"
    weight = 3

    [[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/tags/blog/"
    weight = 5

    [[menu.main]]
    name = "Libri"
    parent = "blog"
    url = "libreria/"
    weight = 5

    [[menu.main]]
    name = "Lifestyle"
    parent = "blog"
    url = "lifestyle/"
    weight = 5

    [[menu.main]]
    name = "Med & Tech"
    url = "med-tech/"
    weight = 6

    [[menu.main]]
    name = "Chi sono"
    url = "about/"
    weight = 7

[params.social]
    twitter       = "np_melanogaster"
    instagram     = "npmelano"
    youtube       = "UCz_ZsgGRbD4tC8_-4Ni78hQ"
    rss           = true
    contatti      = "email/"
    telegram      = "nparisi"