[build]
publish = ""
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = true
    minify = false
[build.processing.js]
    bundle = true
    minify = false
[build.processing.images]
    compress = true