backend:
    name: git-gateway
    branch: master
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: 'racconti-di-viaggio'
    label: 'nuovo Racconti di Viaggio'
    folder: 'content/racconti-viaggio'
    create: true
    slug: '{{slug}}'
    preview_path: {{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: '' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Breve Descrizione/Riassunto', name: 'description', widget: 'string', default: '' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, default: ["diario pressorio", "diario del peso", "nuovo aggiornamento"] }
      - { label: 'Icon', name: 'icon', widget: 'string', default: 'images/icons/general_icon.png | icon_webpressjournal.png | icon_webweightjournal.png' }
      - { label: 'Icon caption', name: 'caption', widget: 'string', default: 'Pressure | Weight | Journal in Cloud' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    
